name: CI Day-1 Hello

<<<<<<< HEAD
on: push
=======
on:
  push:
    branches:
      - main
>>>>>>> dev

jobs:
  hello-job:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> dev
    steps:
      - name: Say Hello
        run: echo "Hello CI/CD ðŸš€"
